# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph_generator.Coordenada')),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ana', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(default=None, max_length=100)),
                ('altitude', models.CharField(default=None, max_length=100)),
                ('bacia', models.CharField(default=None, max_length=100)),
                ('rio', models.CharField(default=None, max_length=100)),
                ('area', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SerieOriginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_temporal_id', models.IntegerField(null=True)),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph_generator.Posto')),
            ],
        ),
        migrations.CreateModel(
            name='SerieTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('dados', models.FloatField(null=True)),
                ('data_e_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph_generator.Posto')),
            ],
            options={
                'verbose_name': 'Série Temporal',
                'verbose_name_plural': 'Séries Temporais',
            },
        ),
    ]
