# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serietemporal',
            unique_together=set([('Id', 'data_e_hora', 'posto')]),
        ),
    ]
